### ISSUE TITLE
Is there any way we can help to translate pfw to English?

### ISSUE THREAD

**Issue by ChrissDeGrece** [gaoqiangz/pfw#2]
pfw looks amazing, can we help somehow to translate it to english?

Also, what's the minimum Powerbuilder version required to run pfw?

**Comment by gaoqiangz** [comment]
It's time to learn Chinese :-)

**Comment by gaoqiangz** [comment]
The minimum version is 10,but 12.5 is best.

**Comment by tmiqpl** [comment]
我中文学的贼溜, 但是我还是不会用pfw.

**Comment by ChrissDeGrece** [comment]
Thanks. 
Is "paint" dw expression supported in PB10?

**Comment by tmiqpl** [comment]
> Thanks.
> Is "paint" dw expression supported in PB10?

paint 最低要求12.5版本

**Comment by figo361** [comment]
哈哈哈
